#Tugas 1 - Crawling Data Twitter

In [2]:
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1

update-alternatives: error: alternative path /usr/bin/python3.7 doesn't exist

In [3]:
!pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.5.0.20230113-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 KB 2.6 MB/s eta 0:00:00
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from snscrape) (2022.7.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.8/dist-packages (from snscrape) (2.25.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from snscrape) (3.9.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.26.14)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.5.0.20230113

In [4]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [5]:
tweet_list = []

In [6]:
#mangambil data twitter dengan TwitterSearchScrapper dan meletakan dalam array
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('sambo since:2022-01-01 until:2023-02-20').get_items()):
  if i>500:
    break
  tweet_list.append([tweet.user.username,tweet.content,tweet.user.location])

<ipython-input-6-a5977d5fb3b1>:5: FutureWarning: content is deprecated, use rawContent instead
  tweet_list.append([tweet.user.username,tweet.content,tweet.user.location])

In [7]:
frame_tweet = pd.DataFrame(tweet_list,columns =['Username','Konten','Lokasi'])
frame_tweet

,Username,Konten,Lokasi
0,_sambo7,@karinaaparicioo wym u take like 3 days😪,alice - cc
1,IwanPangka,@6undul0h mulai gak tau diri...\nSambo salah.....,Bumi Manusia
2,Bank_Aconk,Yasonna Laoly bantah isu pasal KUHP baru terka...,"DKI Jakarta, Indonesia"
3,Ojoklalenya,@retnosetyow4t Kroni sambo x🙄,
4,SamuelSkaggs2,@hodgetwins Can tell me if they see this?,
...,...,...,...
496,SamboGorilla,@MarinaAmezola San Martín murió en Europa.\nPa...,Falkland islands
497,TrevSambo,@destinyzee Oops!!,
498,KingTeejay1987,Sambo behavior,
499,collen_sambo2,@_LeratoMabuza @siqunga This isn’t painful whe...,Global Citizen Based In 🇿🇦
500,sadeeq_wali,@imad_sambo Thank you soo much mutumin a,"Kano, Nigeria"